### PR TITLE
docs(assets-generator): include resizeOptions defaults  (splash)

### PR DESCRIPTION
**Pull request by tripflex**
Added link and tip about resizeOptions for fit

### CODE REVIEW

**Comment by userquin** [comment]
The png is global in the splashebtry here: https://github.com/vite-pwa/assets-generator/blob/main/src/types.ts#L91

**Comment by userquin** [comment]
We should add png to the options in both functions

**Comment by tripflex** [comment]
> We should add png to the options in both functions

Ahhh okay i'll remove those changes to docs

**Comment by tripflex** [comment]
> The png is global in the splash entry here: https://github.com/vite-pwa/assets-generator/blob/main/src/types.ts#L91

Reverted those commits, this PR is just now for a tip about resizeOptions

**Comment by userquin** [comment]
@tripflex I'm updating your PR in assets generation and preparing a new PR to inlcude the missing options.

Can you update also the following entries in CLI page here?
- `resizeOptions: { background: 'white' },` to `resizeOptions: { background: 'white', fit: 'contain' },` in both code snippets here [iOS/iPad Splash Screens](https://vite-pwa-org.netlify.app/assets-generator/cli.html#ios-ipad-splash-screens)
- `darkResizeOptions: {},` to `darkResizeOptions: { background: 'black', fit: 'contain' },` in the code snippet here [Dark Splash Screens](https://vite-pwa-org.netlify.app/assets-generator/cli.html#dark-splash-screens)

I'll change PR title later once the assets generator released.

**Comment by userquin** [comment]
It seems we don't need the TIP

**Comment by userquin** [comment]
@tripflex merging this, If you want any other change feel free to send another PR, thx

**Pull request merged**
