### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by piotr-cz**
As in title

### CODE REVIEW

**Comment by userquin** [comment]
thx, I'll wait to tmr to merge this...

**Comment by piotr-cz** [comment]
By the way, in my setup `workbox-*` files are built inside `/dist/assets` directory.
This means that whole code block is not needed as caching for workbox files is already covered 

https://github.com/vite-pwa/docs/blob/3d29d10c2ab5b3f5154fe00568d1edf705ec7729/deployment/nginx.md?plain=1#L68-L80

**Comment by userquin** [comment]
we should cover default Vite options: if someone using a custom setup should deal with it, we cannot cover all cases (i.e your case)

**Comment by piotr-cz** [comment]
Actually there is only workbox-window file which is created within the `/assets` directory,
It's not specific to my setup, it's the default state.

**Pull request merged**
