### PR TITLE
docs: Added new docs support for internationalization

### PR DESCRIPTION
**Pull request by EnochGao**

### CODE REVIEW

**Comment by userquin** [comment]
I'm not sure to include any translation here (feel free to publish your own translation), we can add a link here.

/cc @antfu

**Comment by antfu** [comment]
Yeah, I'd agree with that as well. It would be too much effort for us to maintain translations.

**Comment by EnochGao** [comment]
I have done some Chinese translations here. https://vite-pwa-org-zh.netlify.app/

**Comment by userquin** [comment]
@EnochGao can you send a new PR adding the translation link? You can check the VP config file in Vite docs folder.

You also need to add the link to pwa docs.

https://github.com/vitejs/vite/blob/main/docs/.vitepress/config.ts#L98

**Pull request closed without merging**
